/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Librarie;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class Librarie_VizualizareCarti extends javax.swing.JFrame {

    /**
     * Creates new form Librarie_VizualizareCarti
     */
    public Librarie_VizualizareCarti() {
        initComponents();
         this.getContentPane().setBackground(new Color(255, 229, 204));
        this.setTitle("Vizualizare");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboFiltrare = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        comboMod = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 30)); // NOI18N
        jLabel1.setText("Vizualizare Carti");

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 20)); // NOI18N
        jLabel2.setText("Filtrare dupa: ");

        comboFiltrare.setBackground(new java.awt.Color(204, 204, 204));
        comboFiltrare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pret", "Titlu", "An Aparitie", "Stoc" }));
        comboFiltrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFiltrareActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jButton1.setText("Vizualizare");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboMod.setBackground(new java.awt.Color(204, 204, 204));
        comboMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crescator", "Descrescator" }));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jButton2.setText("Toate Cartile");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboMod, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(comboMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String filtrare = comboFiltrare.getSelectedItem().toString();
        String mod = comboMod.getSelectedItem().toString();
        String query1 = null,query2 = null,query3,autor = null;
        Statement stmt;
        try {
            Connection con = Conectare.DBConector();
            stmt = (Statement) con.createStatement();
            switch (filtrare) {
                case "Titlu":
                    query1 = "Select * from carti ORDER BY titlu";
                    break;
                case "An Aparitie":
                    query1 = "Select * from carti ORDER BY an_aparitie";
                    break;
                case "Pret":
                    query1 = "Select * from carti ORDER BY pret";
                    break;
                case "Stoc":
                    query1 = "Select * from carti ORDER BY stoc";
                    break;
              
               
            }
            switch(mod){
                case "Crescator":
                    query2=" ASC";
                    break;
                case "Descrescator":
                    query2=" DESC";
                    break;
            }
            query3=query1+query2;
            String query4 = "Select nume,prenume from autor";

            PreparedStatement st2 = con.prepareStatement(query4);

            ResultSet rs2 = st2.executeQuery();
            while(rs2.next()){
                 autor =rs2.getString("nume")+" "+rs2.getString("prenume");
            }
           
            
            PreparedStatement st = con.prepareStatement(query3);
            
            
            ResultSet rs = st.executeQuery();
            Librarie_Afisare lista = new Librarie_Afisare ();
            lista.setVisible(true);
            lista.textAfisare.append("ID CARTE"+"\t"+"Titlu"+"\t"+"Autor"+"\t"+"Editura"+"\t"+"An aparitie"+"\t"+"Pret"+"\t"+"Limba"+"\t"+"Categorie"+"\t"+"Stoc"+"\n");
            while (rs.next()) {
                 lista.textAfisare.append(rs.getString("id_carte")+"\t"+rs.getString("titlu")+"\t"+autor+"\t"+rs.getString("editura")+"\t"
                       +rs.getString("an_aparitie")+"\t"+rs.getString("pret")+"\t"+rs.getString("limba")+"\t"+rs.getString("categorie")+"\t"+rs.getString("stoc")+"\n");
            }
        } 
        
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboFiltrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltrareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFiltrareActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Statement stmt;
         String autor = null;
        try {
            Connection con = Conectare.DBConector();
            stmt = (Statement) con.createStatement();
          
            String query = "Select * from carti";
            String query4 = "Select nume,prenume from autor";

            PreparedStatement st2 = con.prepareStatement(query4);

            ResultSet rs2 = st2.executeQuery();
            while(rs2.next()){
                 autor =rs2.getString("nume")+" "+rs2.getString("prenume");
            }
           
            
            PreparedStatement st = con.prepareStatement(query);
            
            
            ResultSet rs = st.executeQuery();
            Librarie_Afisare lista = new Librarie_Afisare ();
            lista.setVisible(true);
            lista.textAfisare.append("ID CARTE"+"\t"+"Titlu"+"\t"+"Autor"+"\t"+"Editura"+"\t"+"An aparitie"+"\t"+"Pret"+"\t"+"Limba"+"\t"+"Categorie"+"\t"+"Stoc"+"\n");
            while (rs.next()) {
                 lista.textAfisare.append(rs.getString("id_carte")+"\t"+rs.getString("titlu")+"\t"+autor+"\t"+rs.getString("editura")+"\t"
                       +rs.getString("an_aparitie")+"\t"+rs.getString("pret")+"\t"+rs.getString("limba")+"\t"+rs.getString("categorie")+"\t"+rs.getString("stoc")+"\n");
            }
        } 
        
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librarie_VizualizareCarti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librarie_VizualizareCarti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librarie_VizualizareCarti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librarie_VizualizareCarti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Librarie_VizualizareCarti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboFiltrare;
    private javax.swing.JComboBox<String> comboMod;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
