/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Librarie;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class Librarie_AdaugareCarte extends javax.swing.JFrame {

    /**
     * Creates new form Librarie_AdaugareCarte
     */
    public Librarie_AdaugareCarte() {
        initComponents();
        this.getContentPane().setBackground(new Color(255, 229, 204));
        this.setTitle("Adaugare Carte");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        Statement stmt;
        try {
            Connection con = Conectare.DBConector();
            stmt = (Statement) con.createStatement();
            String query = "Select nume,prenume from autor";

            PreparedStatement st = con.prepareStatement(query);

            ResultSet rs = st.executeQuery();

            while (rs.next()) {
                comboAutor.addItem(rs.getString("nume") + " " + rs.getString("prenume"));

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textIdCarte = new javax.swing.JTextField();
        textTitlu = new javax.swing.JTextField();
        textEditura = new javax.swing.JTextField();
        textAn = new javax.swing.JTextField();
        textPret = new javax.swing.JTextField();
        comboLimba = new javax.swing.JComboBox<>();
        textCategorie = new javax.swing.JTextField();
        textStoc = new javax.swing.JTextField();
        butonOk = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        comboAutor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 30)); // NOI18N
        jLabel1.setText("ADAUGARE CARTE");

        jLabel2.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel2.setText("ID carte:");

        jLabel3.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel3.setText("Titlu:");

        jLabel4.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel4.setText("Editura:");

        jLabel5.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel5.setText("An aparitie:");

        jLabel6.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel6.setText("Pret:");

        jLabel7.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel7.setText("Limba:");

        jLabel8.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel8.setText("Categorie:");

        jLabel9.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel9.setText("Stoc:");

        textIdCarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdCarteActionPerformed(evt);
            }
        });
        textIdCarte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textIdCarteKeyTyped(evt);
            }
        });

        textAn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAnKeyTyped(evt);
            }
        });

        textPret.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPretKeyTyped(evt);
            }
        });

        comboLimba.setBackground(new java.awt.Color(204, 204, 204));
        comboLimba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Romana", "Engleza", "Franceza", "Italiana", "Spaniola" }));

        textStoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textStocKeyTyped(evt);
            }
        });

        butonOk.setBackground(new java.awt.Color(204, 204, 204));
        butonOk.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        butonOk.setText("ADAUGA");
        butonOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonOkActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel10.setText("Autor:");

        comboAutor.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textPret)
                            .addComponent(textIdCarte, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEditura, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboLimba, 0, 106, Short.MAX_VALUE)
                            .addComponent(textTitlu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCategorie)
                            .addComponent(textStoc)
                            .addComponent(comboAutor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(butonOk)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textIdCarte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textTitlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textEditura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboLimba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textStoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addComponent(butonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonOkActionPerformed
        String titlu, editura, categorie, limba;
        int id_carte = 0, an_aparitie = 0, pret = 0, stoc = 0, id_autor = 0;
        Statement stmt = null;
        PreparedStatement ps = null;
        boolean ok = false;
        titlu = textTitlu.getText();
        editura = textEditura.getText();
        categorie = textCategorie.getText();
        limba = comboLimba.getSelectedItem().toString();
        try {
            id_carte = Integer.parseInt(textIdCarte.getText());
            an_aparitie = Integer.parseInt(textAn.getText());
            pret = Integer.parseInt(textPret.getText());
            stoc = Integer.parseInt(textStoc.getText());
        } catch (NumberFormatException ex) {

        }
        try {
            Connection con = Conectare.DBConector();
            stmt = (Statement) con.createStatement();
            if (textTitlu.getText().length() == 0 || textEditura.getText().length() == 0 || textCategorie.getText().length() == 0 || textIdCarte.getText().length() == 0
                    || textAn.getText().length() == 0 || textPret.getText().length() == 0 || textStoc.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "TOATE CAMPURILE SUNT OBLIGATORII!", "Error", 1);
                ok = false;
            } else {
                ok = true;
            }
            if(ok==true){
                ps = con.prepareStatement("INSERT INTO carti(id_carte, titlu, id_autor, editura, an_aparitie, pret, limba, categorie, stoc) VALUES (?,?,?,?,?,?,?,?,?)");
                PreparedStatement st = con.prepareStatement("Select id_autor from autor where nume=? and prenume=?");
                 String nume = comboAutor.getSelectedItem().toString();
                String[] numebun = nume.split(" ");
                st.setString(1, numebun[0].toString());
                st.setString(2, numebun[1].toString());
                st.executeQuery();
                ResultSet rs = st.getResultSet();
               
                while (rs.next()) {
                    id_autor=Integer.parseInt(rs.getString(1));
                    
                }
                ps.setInt(1,id_carte);
                ps.setInt(3, id_autor);
                ps.setString(2,titlu);
                ps.setString(4, editura);
                ps.setInt(5,an_aparitie);
                ps.setInt(6,pret);
                ps.setString(7,limba);
                ps.setString(8, categorie);
                ps.setInt(9,stoc);
                int i = ps.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(null, "Cartea a fost introdusa in baza de date!");
                }
                
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_butonOkActionPerformed

    private void textIdCarteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIdCarteKeyTyped
        // TODO add your handling code here:
        Metode metoda = new Metode();
         metoda.check(evt);
         if(textIdCarte.getText().length()>4){
           evt.consume();
         }
    }//GEN-LAST:event_textIdCarteKeyTyped

    private void textAnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAnKeyTyped
        // TODO add your handling code here:
         Metode metoda = new Metode();
         metoda.check(evt);
         if(textAn.getText().length()>3){
           evt.consume();
         }
    }//GEN-LAST:event_textAnKeyTyped

    private void textPretKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPretKeyTyped
        // TODO add your handling code here:
         Metode metoda = new Metode();
         metoda.check(evt);
         if(textPret.getText().length()>4){
           evt.consume();
         }
    }//GEN-LAST:event_textPretKeyTyped

    private void textStocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textStocKeyTyped
        // TODO add your handling code here:
         Metode metoda = new Metode();
         metoda.check(evt);
         if(textStoc.getText().length()>4){
           evt.consume();
         }
    }//GEN-LAST:event_textStocKeyTyped

    private void textIdCarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdCarteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdCarteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librarie_AdaugareCarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librarie_AdaugareCarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librarie_AdaugareCarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librarie_AdaugareCarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Librarie_AdaugareCarte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonOk;
    private javax.swing.JComboBox<String> comboAutor;
    private javax.swing.JComboBox<String> comboLimba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textAn;
    private javax.swing.JTextField textCategorie;
    private javax.swing.JTextField textEditura;
    private javax.swing.JTextField textIdCarte;
    private javax.swing.JTextField textPret;
    private javax.swing.JTextField textStoc;
    private javax.swing.JTextField textTitlu;
    // End of variables declaration//GEN-END:variables
}
