/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Librarie;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class Librarie_CautareCarte extends javax.swing.JFrame {

    /**
     * Creates new form Librarie_CautareCarte
     */
    public Librarie_CautareCarte() {
        initComponents();
        this.getContentPane().setBackground(new Color(255, 229, 204));
        this.setTitle("Cautare Carte");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboSelectie = new javax.swing.JComboBox<>();
        textCautare = new javax.swing.JTextField();
        butonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 30)); // NOI18N
        jLabel1.setText("Cautare carte");

        jLabel2.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel2.setText("Dupa:");

        comboSelectie.setBackground(new java.awt.Color(204, 204, 204));
        comboSelectie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cod Carte", "Titlu", "Editura", "An aparitie", "Pret", "Stoc" }));

        butonOk.setBackground(new java.awt.Color(204, 204, 204));
        butonOk.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        butonOk.setText("CAUTA");
        butonOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboSelectie, 0, 109, Short.MAX_VALUE)
                            .addComponent(textCautare))))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butonOk)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboSelectie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(textCautare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(butonOk)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonOkActionPerformed
        String selectie = comboSelectie.getSelectedItem().toString();
        
       
        Statement stmt;
        String query=null;
        String autor=null;
        try {
            Connection con = Conectare.DBConector();
            stmt = (Statement) con.createStatement();
            switch (selectie) {
                case "Cod Carte":
                    query = "Select * from carti where id_carte=?";
                    break;
                case "Titlu":
                    query = "Select * from carti where titlu=?";
                    break;
                case "Editura":
                    query = "Select * from carti where editura=?";
                    break;
                case "An aparitie":
                    query = "Select * from carti where an_aparitie=?";
                    break;
                case "Pret":
                    query = "Select * from carti where pret=?";
                    break;
                case "Stoc":
                    query = "Select * from carti where stoc=?";
                    break;
               
            }
            String query2 = "Select nume,prenume from autor";

            PreparedStatement st2 = con.prepareStatement(query2);

            ResultSet rs2 = st2.executeQuery();
            while(rs2.next()){
                 autor =rs2.getString("nume")+" "+rs2.getString("prenume");
            }
           
            
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, textCautare.getText());
            
            ResultSet rs = st.executeQuery();
            Librarie_Afisare lista = new Librarie_Afisare ();
            lista.setVisible(true);
            lista.textAfisare.append("ID CARTE"+"\t"+"Titlu"+"\t"+"Autor"+"\t"+"Editura"+"\t"+"An aparitie"+"\t"+"Pret"+"\t"+"Limba"+"\t"+"Categorie"+"\t"+"Stoc"+"\n");
            while (rs.next()) {
                 lista.textAfisare.append(rs.getString("id_carte")+"\t"+rs.getString("titlu")+"\t"+autor+"\t"+rs.getString("editura")+"\t"
                       +rs.getString("an_aparitie")+"\t"+rs.getString("pret")+"\t"+rs.getString("limba")+"\t"+rs.getString("categorie")+"\t"+rs.getString("stoc")+"\n");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_butonOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librarie_CautareCarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librarie_CautareCarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librarie_CautareCarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librarie_CautareCarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Librarie_CautareCarte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonOk;
    private javax.swing.JComboBox<String> comboSelectie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textCautare;
    // End of variables declaration//GEN-END:variables
}
